# Generated by Django 5.1.7 on 2025-03-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Housing & Utilities", "🏠 Housing & Utilities"),
                            ("Food & Groceries", "🛒 Food & Groceries"),
                            ("Transportation", "🚗 Transportation"),
                            ("Health & Wellness", "🏥 Health & Wellness"),
                            ("Entertainment & Leisure", "🎬 Entertainment & Leisure"),
                            ("Education & Learning", "📚 Education & Learning"),
                            ("Gifts & Donations", "🎁 Gifts & Donations"),
                            ("Insurance & Taxes", "🏦 Insurance & Taxes"),
                            ("Business & Work", "💼 Business & Work"),
                            ("Travel & Vacations", "✈️ Travel & Vacations"),
                            ("Pets & Animals", "🐾 Pets & Animals"),
                            (
                                "Subscriptions & Memberships",
                                "📅 Subscriptions & Memberships",
                            ),
                            ("Miscellaneous", "🔄 Miscellaneous/Others"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("expense", "Expense"), ("income", "Income")],
                        max_length=7,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
