# Generated by Django 5.1.7 on 2025-03-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date_created",
            field=models.DateTimeField(),
        ),
    ]
