# Generated by Django 5.1.7 on 2025-03-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_transaction_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("Expense", "Expense"), ("Income", "Income")], max_length=7
            ),
        ),
    ]
